from abc import ABC, abstractmethod
import numpy as np


class AbstractErrorEstimator(ABC):
    @abstractmethod
    def estimate(self, mu: np.array, cov: np.array, allocation: np.array, optimal_allocation: np.array) -> float:
        """
        Measures how far the allocation is from the desired allocation. See section 4.5 of the "A Robust Estimator of
        the Efficient Frontier" paper.
        @param mu: Expected return vector
        @param cov: Expected covariance matrix
        @param allocation: Portfolio allocation generated by an Optimizer using a simulated mu and covariance matrix
        @param optimal_allocation: Optimal portfolio allocation generated by an Optimizer using the original mu and covariance matrix
        @return
        """
        pass


class ExpectedOutcomeErrorEstimator(AbstractErrorEstimator):
    """Error Estimator that calculates the mean difference in expected outcomes"""

    def estimate(self, mu: np.array, cov: np.array, allocation: np.array, optimal_allocation: np.array) -> float:
        return np.dot(optimal_allocation - allocation, mu)


class VarianceErrorEstimator(AbstractErrorEstimator):
    """Error Estimator that calculates the mean difference in variance"""

    def estimate(self, mu: np.array, cov: np.array, allocation: np.array, optimal_allocation: np.array) -> float:
        return np.dot(optimal_allocation - allocation, np.dot(optimal_allocation - allocation, cov))
