from abc import ABC, abstractmethod
import numpy as np


class AbstractErrorEstimator(ABC):
    @abstractmethod
    def estimate(self, allocation: np.array, optimal_allocation: np.array) -> float:
        """
        Measures how far the allocation is from the desired allocation. See section 4.5 of the "A Robust Estimator of
        the Efficient Frontier" paper.
        @param allocation: Portfolio allocation generated by an Optimizer
        @param optimal_allocation: Optmimal allocation
        @return
        """
        pass
